name: WordPress Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]
        wp: [latest, "6.0", "5.9", "5.8"]
        
    name: PHP ${{ matrix.php }} / WordPress ${{ matrix.wp }}
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist"

      - name: Create bin directory if it doesn't exist
        run: mkdir -p bin

      - name: Download WordPress Tests
        run: |
          if [ ! -f bin/install-wp-tests.sh ]; then
            curl -s https://raw.githubusercontent.com/wp-cli/scaffold-command/master/templates/install-wp-tests.sh > bin/install-wp-tests.sh
            chmod +x bin/install-wp-tests.sh
          fi

      - name: Setup WordPress Test Environment
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp }}

      - name: Run PHPCS
        run: composer phpcs

      - name: Run PHPUnit
        run: vendor/bin/phpunit
